/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ModalLeaderBoard: typeof import('./src/components/ModalLeaderBoard.vue')['default']
    ModalLoading: typeof import('./src/components/ModalLoading.vue')['default']
    ModalLoginWithGoogle: typeof import('./src/components/ModalLoginWithGoogle.vue')['default']
    ModalQuiz: typeof import('./src/components/ModalQuiz.vue')['default']
    ModalSettings: typeof import('./src/components/ModalSettings.vue')['default']
    ModalUserProfile: typeof import('./src/components/ModalUserProfile.vue')['default']
    UserHelper: typeof import('./src/components/UserHelper.vue')['default']
  }
}
